# Use an official Python runtime as the parent image
FROM python:3.8 AS builder

# Set the working directory in the container to /webapp
WORKDIR /webapp

# Copy the current directory contents into the container at /webapp
COPY ./requirements.txt requirements.txt
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt && rm -rf /root/.cache/pip/

# Make port 7860 available to the world outside this container
EXPOSE 7860

# Run webapp.py when the container launches
CMD ["python3", "webapp.py"]
